modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="jigseu"
version="3.0.0"
displayName="Jigsaw event utils"
credits="Elephantum Fragariarum"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Jigsaw squad"

[[dependencies.jigseu]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




